version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/docker-www/data/mysql:/var/lib/mysql

  blog:
    image: uspgamedev/wordpress
    restart: always
    links:
      - db:mysql
    volumes:
      - /var/docker-www/config:/host
      - /var/docker-www/data/wordpress/wp-content:/var/www/wp-content
      - /etc/ssmtp:/etc/ssmtp:ro
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: uspgamedev_wordpress

  wiki:
    image: mediawiki:1.37
    restart: always
    links:
      - db:mysql
    volumes:
      - /var/docker-www/config:/host
      #- /var/docker-www/data/mediawiki:/var/www-shared/html
      - /var/docker-www/data/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - /var/docker-www/data/mediawiki/images:/var/www/html/images
      - /etc/ssmtp:/etc/ssmtp:ro
    environment:
      MEDIAWIKI_DB_HOST: mysql:3306
      MEDIAWIKI_DB_NAME: uspgamedev_wiki

  bookstack:
    image: solidnerd/bookstack:23.2.3
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    env_file: .env
    environment:
      DB_HOST: mysql:3306
      DB_DATABASE: uspgamedev_bookstack
      #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
      APP_URL: https://usp.game.dev.br/wiki2
    volumes:
      - /var/docker-www/bookstack/.env:/var/www/bookstack/.env
      - /var/docker-www/bookstack/uploads:/var/www/bookstack/public/uploads
      - /var/docker-www/bookstack/storage-uploads:/var/www/bookstack/storage/uploads
    ports:
      - "8081:8080"

  node-exporter:
    image: prom/node-exporter:v0.18.0
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'

  proxy:
    image: uspgamedev/nginx
    restart: always
    links:
      - blog:blog
      - wiki:wikia
      - node-exporter:node-exporter
    volumes:
      - /var/docker-www/data/discourse/standalone:/var/discourse
      - /var/docker-www/static:/var/www/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/docker-www/acme-challenge:/var/acme-challenge:ro
    ports:
      - 80:80
      - 443:443
