version: '2'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - /var/docker-www/data/mysql:/var/lib/mysql

  blog:
    image: uspgamedev/wordpress
    restart: always
    links:
      - db:mysql
    volumes:
      - /var/docker-www/config:/host
      - /var/docker-www/data/wordpress/wp-content:/var/www/wp-content
      - /etc/ssmtp:/etc/ssmtp:ro
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: uspgamedev_wordpress

  wiki:
    image: uspgamedev/mediawiki
    restart: always
    links:
      - db:mysql
    working_dir: /var/www/html/mediawiki
    volumes:
      - /var/docker-www/config:/host
      - /var/docker-www/data/mediawiki:/var/www-shared/html
      - /etc/ssmtp:/etc/ssmtp:ro
    environment:
      MEDIAWIKI_DB_HOST: mysql:3306
      MEDIAWIKI_DB_NAME: uspgamedev_wiki

  chat:
    image: uspgamedev/mattermost
    restart: always
    volumes:
      - /var/docker-www/config:/host:ro
    environment:
      DB_HOST: uspgamedev.org

  proxy:
    image: uspgamedev/nginx
    restart: always
    links:
      - blog:blog
      - wiki:wikia
      - chat:chat
    volumes:
      - /var/docker-www/data/discourse/standalone:/var/discourse
      - /var/docker-www/static:/var/www/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/docker-www/acme-challenge:/var/acme-challenge:ro
    ports:
      - 80:80
      - 443:443
