version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/docker-www/data/mysql:/var/lib/mysql

  blog:
    image: uspgamedev/wordpress
    restart: always
    links:
      - db:mysql
    volumes:
      - /var/docker-www/config:/host
      - /var/docker-www/data/wordpress/wp-content:/var/www/wp-content
      - /etc/ssmtp:/etc/ssmtp:ro
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: uspgamedev_wordpress

  wiki:
    image: uspgamedev/mediawiki
    restart: always
    links:
      - db:mysql
    working_dir: /var/www/html/mediawiki
    volumes:
      - /var/docker-www/config:/host
      - /var/docker-www/data/mediawiki:/var/www-shared/html
      - /etc/ssmtp:/etc/ssmtp:ro
    environment:
      MEDIAWIKI_DB_HOST: mysql:3306
      MEDIAWIKI_DB_NAME: uspgamedev_wiki

  chat:
    image: uspgamedev/mattermost
    restart: always
    volumes:
      - /var/docker-www/config:/host:ro
      - /var/docker-www/data/mattermost:/mattermost/data
      - /var/docker-www/config/mattermost:/mattermost/config
    environment:
      DB_HOST: uspgamedev.org

  node-exporter:
    image: prom/node-exporter:v0.18.0
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'

  grafana:
    image: grafana/grafana:6.1.6
    # links:
    #   - db:mysql

    volumes:
      - /var/docker-www/data/grafana:/var/lib/grafana

    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: "grafana.uspgamedev.org"
      # GF_DATABASE_TYPE: mysql
      # GF_DATABASE_HOST: mysql:3306
      # GF_DATABASE_USER: root

  proxy:
    image: uspgamedev/nginx
    restart: always
    links:
      - blog:blog
      - wiki:wikia
      - chat:chat
      - node-exporter:node-exporter
      - grafana:grafana
    volumes:
      - /var/docker-www/data/discourse/standalone:/var/discourse
      - /var/docker-www/static:/var/www/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/docker-www/acme-challenge:/var/acme-challenge:ro
    ports:
      - 80:80
      - 443:443
